




const phoneDB = [
    {
        'category': '#telephone',
        'src1': '../../img/catalog/phone/apple/1/ip11-b.jpg',
        'radio1': 'Серо-бур-зеленый',
        'src2': '../../img/catalog/phone/apple/1/ip11-p.jpg',
        'radio2': 'цвет штор',
        'src3': '../../img/catalog/phone/apple/1/ip11-r.jpg',
        'radio3': 'морской каприз',
        'src4': '../../img/catalog/phone/apple/1/ip11-w.jpg',
        'radio4': 'фиолетовый батальон',
        'length': 4,
        'alt': 'no picture',
        'title': 'iphone 13 pro max turbo',
        'subtitle': 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem nostrum excepturi esse lorem ',
        'price': 1650,
        'data': '14.05.2017',
        'brand': 'apple',
        'id': 1,
    },
    {
        'category': '#telephone',
        'src1': '../../img/catalog/phone/apple/2/ip13m-b.jpg',
        'radio1': 'восточная пупырка',
        'src2': '../../img/catalog/phone/apple/2/ip13m-black.jpg',
        'radio2': 'красный металл',
        'src3': '../../img/catalog/phone/apple/2/ip13m-p.jpg',
        'radio3': 'мухоморно синий',
        'src4': '../../img/catalog/phone/apple/2/ip13m-w.jpg',
        'radio4': 'убежавшая лошадь',
        'length': 4,
        'alt': 'picture is out',
        'title': 'iphone 45 XXX',
        'subtitle': 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem nostrum excepturi esse ipisicing elit. Dolorem nostrum excepturi',
        'price': 2000,
        'data': '14.12.2018',
        'brand': 'apple',
        'id': 2,
    },
    {
        'category': '#telephone',
        'src1': '../../img/catalog/phone/xiomi/1/9x-bl.jpg',
        'radio1': 'китайско зеленый',
        'src2': '../../img/catalog/phone/xiomi/1/9x-gr.jpg',
        'radio2': 'бурчатый',
        'src3': '../../img/catalog/phone/xiomi/1/9x-or.jpg',
        'radio3': 'хромая косуля',
        'src4': '../../img/catalog/phone/xiomi/1/9x-pu.jpg',
        'radio4': 'воздушный бздыщ...',
        'length': 4,
        'alt': 'get out',
        'title': 'xiaomi in hun hen 10x',
        'subtitle': 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem nostrum excepturi esse lorem11 ',
        'price': 1100,
        'data': '01.12.2012',
        'brand': 'xiaomi',
        'id': 3,
    },
    {
        'category': '#telephone',
        'src1': '../../img/catalog/phone/other/1/h50l-bl.jpg',
        'radio1': 'космический пук',
        'src2': '../../img/catalog/phone/other/1/h50l-black.jpg',
        'radio2': 'хромой стол',
        'src3': '../../img/catalog/phone/other/1/h50l-gr.jpg',
        'radio': 'кинзово зеленый',
      
        'length': 3,
        'alt': 'not',
        'title': 'Fake Iphone 1',
        'subtitle': 'Lorem  excepturi esse lorem11 ',
        'price': 5000,
        'data': '19.10.2001',
        'brand': 'other',
        'id': 4,
    },
    {
        'category': '#telephone',
        'src1': '../../img/catalog/phone/apple/3/ip13pro-blue.jpg',
        'radio1': 'цвет козы',
        'src2': '../../img/catalog/phone/apple/3/ip13pro-g.jpg',
        'radio2': 'небесно ночной',
        'src3': '../../img/catalog/phone/apple/3/ip13pro-green.jpg',
        'radio3': 'оранжево капризный',
        'src4': '../../img/catalog/phone/apple/3/ip13pro-w.jpg',
        'radio4': 'научно популярный',
        'length': 4,
        'alt': 'not',
        'title': 'iphone 45z COOL',
        'subtitle': 'Lorem ipsum dol Dolorem nostrum excepturi',
        'price': 3500,
        'data': '14.01.2118',
        'brand': 'apple',
        'id': 5,
    },
    {
        'category': '#telephone',
        'src1': '../../img/catalog/phone/xiomi/2/10s-gr.jpg',
        'radio1': 'очковый',
        'src2': '../../img/catalog/phone/xiomi/2/10s-sk.jpg',
        'radio2': 'бородатый',
        'src3': '../../img/catalog/phone/xiomi/2/10s-wh.jpg',
        'radio3': 'сомово-зеленый',
        
        'length': 3,
        'alt': 'not',
        'title': 'Xiomi pro100 lite',
        'subtitle': 'Lorem ipsum dolor sit amet consectetur adipisic11 ',
        'price': 2500,
        'data': '07.07.2077',
        'brand': 'xiaomi',
        'id': 6,
    },
    {
        'category': '#telephone',
        'src1': '../../img/catalog/phone/other/2/other1.jpg',
        'radio1': 'зеленый Ёж',
        'src2': '../../img/catalog/phone/other/2/other2.webp',
        'radio2': 'летящая улитка',
        'src3': '../../img/catalog/phone/other/2/other3.jpg',
        'radio3': 'динозавровавый',
        'src4': '../../img/catalog/phone/other/2/other4.jpg',
        'radio4': 'липово-железный',
        'length': 4,
        'alt': 'not',
        'title': 'Волшебный телефон',
        'subtitle': 'Lorem ipsum dolor sit amet consectetur adipisic11 ',
        'price': 11000,
        'data': '02.02.2022',
        'brand': 'other',
        'id': 7,
    },
    {
        'category': '#telephone',
        'src1': '../../img/catalog/phone/xiomi/3/12l-bl.jpg',
        'radio1': 'красного словца',
        'src2': '../../img/catalog/phone/xiomi/3/12l-gr.jpg',
        'radio2': 'зеленого свинца',
        'src3': '../../img/catalog/phone/xiomi/3/12l-pink.jpg',
        'radio3': 'малиновый',
        
        'length': 3,
        'alt': 'not',
        'title': 'Xiomi Road 60',
        'subtitle': 'Lorem ipsum dolor sit amet consectetur adipisic11 ',
        'price': 7500,
        'data': '14.10.2013',
        'brand': 'xiaomi',
        'id': 8,
    },
    {
        'category': '#telephone',
        'src1': '../../img/catalog/phone/xiomi/4/11n-bl.jpg',
        'radio1': 'крипово-зеленый',
        'src2': '../../img/catalog/phone/xiomi/4/11n-gr.jpg',
        'radio2': 'колоночный',
        'src3': '../../img/catalog/phone/xiomi/4/11n-sk.jpg',
        'radio3': 'самовыдуманный',
        
        'length': 3,
        'alt': 'not',
        'title': 'Xiomi Cruel',
        'subtitle': 'Lorem ipsum dolor sit amet consectetur adipisic11 ',
        'price': 7700,
        'data': '10.12.2018',
        'brand': 'xiaomi',
        'id': 9,
    },
    {
        'category': '#telephone',
        'src1': '../../img/catalog/phone/apple/4/ip14-b.jpg',
        'radio1': 'прозрачный',
        'src2': '../../img/catalog/phone/apple/4/ip14-puple.jpg',
        'radio2': 'фиолетовый',
        'src3': '../../img/catalog/phone/apple/4/ip14-r.jpg',
        'radio3': 'паркетный',
        'src4': '../../img/catalog/phone/apple/4/ip14-w.jpg',
        'radio4': 'круизный',
        'length': 4,
        'alt': 'not',
        'title': 'iphone Galaxy s21',
        'subtitle': 'Lorem ipsum dol Dolorem nostrum excepturi',
        'price': 800,
        'data': '22.07.2011',
        'brand': 'apple',
        'id': 10,
    },
    //case
    {
        'category': '#caseCards',
        'src1': '../../img/catalog/case/other/1/oppo1.jpg',
        'radio1': 'фисташковый',
        'src2': '../../img/catalog/case/other/1/oppo2.webp',
        'radio2': 'гранулированый',
        'src3': '../../img/catalog/case/other/1/oppo3.jpg',
        'radio3': 'бородатый',
        'src4': '../../img/catalog/case/other/1/oppo4.webp',
        'radio4': 'шоколадный',
        'length': 4,
        'alt': 'not',
        'title': 'Oppo reno 2z Case',
        'subtitle': 'Lorem ipsum dol Dolorem nostrum excepturi ipsum dol Dolorem nostrum excepturi',
        'price': 8888,
        'data': '28.07.2018',
        'brand': 'other',
        'id': 11,
    },
    {
        'category': '#caseCards',
        'src1': '../../img/catalog/case/xiomi/1/1.webp',
        'radio1': 'владленовский',
        'src2': '../../img/catalog/case/xiomi/1/2gr.webp',
        'radio2': 'каспийский',
        'src3': '../../img/catalog/case/xiomi/1/2red.webp',
        'radio3': 'лиловый',
        'src4': '../../img/catalog/case/xiomi/1/2redblue.webp',
        'radio4': 'листиковый',
        'length': 4,
        'alt': 'not',
        'title': 'Xiaomi mi777',
        'subtitle': 'Lorem ipsum dol Dolorem nostrum excepturi ipsum dol Dolorem nostrum excepturi. lorem ipsum dol Dolorem nostrum excepturi',
        'price': 123,
        'data': '28.12.2022',
        'brand': 'xiaomi',
        'id': 12,
    },
    {
        'category': '#caseCards',
        'src1': '../../img/catalog/case/iphone/1/ip1-black.webp',
        'radio1': 'белый',
        'src2': '../../img/catalog/case/iphone/1/ip1-pink.webp',
        'radio2': 'тестовый',
        'src3': '../../img/catalog/case/iphone/1/ip1-red.webp',
        'radio3': 'клавиатурный',
        'src4': '../../img/catalog/case/iphone/1/ip1-ye.webp',
        'radio4': 'мочковый',
        'length': 4,
        'alt': 'not',
        'title': 'Apple Space X-blue',
        'subtitle': 'Lorem ipsum dol  lorem ipsum dol Dolorem nostrum excepturi',
        'price': 1230,
        'data': '28.10.2024',
        'brand': 'apple',
        'id': 13,
    },
    {
        'category': '#caseCards',
        'src1': '../../img/catalog/case/iphone/2/1.webp',
        'radio1': 'оконный',
        'src2': '../../img/catalog/case/iphone/2/2.webp',
        'radio2': 'безфантазийный',
        'src3': '../../img/catalog/case/iphone/2/3.webp',
        'radio3': 'уставший',
        
        'length': 3,
        'alt': 'not',
        'title': 'Apple Stive Jobs',
        'subtitle': 'Lorem ipsum dol  lorem ipsum dol Dolorem nostrum excepturi Lorem ipsum dol  lorem ipsum dol Dolorem nostrum excepturi Lorem ipsum dol  lorem ipsum dol Dolorem nostrum excepturi',
        'price': 9999,
        'data': '06.01.1988',
        'brand': 'apple',
        'id': 14,
    },
    {
        'category': '#caseCards',
        'src1': '../../img/catalog/case/xiomi/2/1red.webp',
        'radio1': 'питнистый',
        'src2': '../../img/catalog/case/xiomi/2/2black.webp',
        'radio2': 'рабочий',
        'src3': '../../img/catalog/case/xiomi/2/2blue.webp',
        'radio3': 'я устал придумывать',
        'src4': '../../img/catalog/case/xiomi/2/2brown.webp',
        'radio4': 'болит голова',
        'length': 4,
        'alt': 'not',
        'title': 'Xiaomi Rus 3',
        'subtitle': 'Lorem ipsum dol Dolorem nostrum excepturi ipsum dol Dolorem nostrum excepturi. lorem ipsum dol Dolorem nostrum excepturi',
        'price': 8800,
        'data': '14.01.2020',
        'brand': 'xiaomi',
        'id': 15,
    },
    {
        'category': '#caseCards',
        'src1': '../../img/catalog/case/other/2/oppo1.webp',
        'radio1': 'наушниковый',
        'src2': '../../img/catalog/case/other/2/oppo2.webp',
        'radio2': 'пассатовый',
        'src3': '../../img/catalog/case/other/3/g3.webp',
        'radio3': 'вольвовый',
       
        'length': 3,
        'alt': 'not',
        'title': 'Oppo  18 Y',
        'subtitle': 'Lorem ipsum dol Dolorem nostrum excepturi ipsum dol Dolorem nostrum excepturi',
        'price': 1150,
        'data': '28.03.2022',
        'brand': 'other',
        'id': 16,
    },
    {
        'category': '#caseCards',
        'src1': '../../img/catalog/case/other/3/g1.webp',
        'radio1': 'семерочный',
        'src2': '../../img/catalog/case/other/3/g2.webp',
        'radio2': 'задуманный',
        'src3': '../../img/catalog/case/other/3/g3.webp',
        'radio3': 'зачемный',
       
        'length': 3,
        'alt': 'not',
        'title': 'Oppo  18 Y',
        'subtitle': 'Lorem ipsum dol Dolorem nostrum excepturi ipsum dol Dolorem nostrum excepturi',
        'price': 1150,
        'data': '28.03.2022',
        'brand': 'other',
        'id': 17,
    },
    {
        'category': '#caseCards',
        'src1': '../../img/catalog/case/other/4/t1.webp',
        'radio1': 'мной',
        'src2': '../../img/catalog/case/other/4/t2.webp',
        'radio2': 'мный',
        'src3': '../../img/catalog/case/other/4/t3.jpg',
        'radio3': 'мнуй',
       
        'length': 3,
        'alt': 'not',
        'title': 'Oppo  88-00',
        'subtitle': 'Lorem ipsum dol Dolorem nostrum excepturi ipsum dol Dolorem nostrum excepturi Lorem ipsum dol Dolorem nostrum excepturi ipsum dol Dolorem nostrum excepturi',
        'price': 1150,
        'data': '28.12.1965',
        'brand': 'other',
        'id': 18,
    },
    {
        'category': '#caseCards',
        'src1': '../../img/catalog/case/xiomi/3/x1.jpg',
        'radio1': 'головной',
        'src2': '../../img/catalog/case/xiomi/3/x2.jpg',
        'radio2': 'синего неба',
        'src3': '../../img/catalog/case/xiomi/3/x3.jpg',
        'radio3': 'зеленого дерева',
        
        'length': 3,
        'alt': 'not',
        'title': 'Xiaomi Mi note S12',
        'subtitle': 'Lorem ipsum dol Dolorem nostrum excepturi ipsum dol Dolorem nostrum excepturi. ',
        'price': 18000,
        'data': '10.01.2020',
        'brand': 'xiaomi',
        'id': 19,
    },
    {
        'category': '#caseCards',
        'src1': '../../img/catalog/case/iphone/3/se1-bl.jpg',
        'radio1': 'сине-зеленый',
        'src2': '../../img/catalog/case/iphone/3/se1-gr.jpg',
        'radio2': 'рыжий',
        'src3': '../../img/catalog/case/iphone/3/se1-pink.jpg',
        'radio3': 'кошачий',
        'src3': '../../img/catalog/case/iphone/3/se1-red.jpg',
        'radio3': 'уссовый',
        
        'length': 4,
        'alt': 'not',
        'title': 'Apple Ilon Mask 2Pro',
        'subtitle': 'Lorem i ipsum dol  lorem ipsum dol Dolorem nostrum excepturi',
        'price': 30999,
        'data': '31.12.1999',
        'brand': 'apple',
        'id': 20,
    },
    {
        'category': '#caseCards',
        'src1': '../../img/catalog/case/other/husbic/h1.webp',
        'radio1': 'небольшой',
        'src2': '../../img/catalog/case/other/husbic/h2.webp',
        'radio2': 'низкий',
        'src3': '../../img/catalog/case/other/husbic/h3.webp',
        'radio3': 'хасбиковый',
        'src3': '../../img/catalog/case/other/husbic/h4.webp',
        'radio3': 'знаменитый',
       
        'length': 4,
        'alt': 'not',
        'title': 'Husbic ProStyle',
        'subtitle': 'Lorem ipsum excepturi ipsum dol Dolorem nostrum excepturi',
        'price': 777,
        'data': '02.12.1979',
        'brand': 'red',
        'id': 21,
    },
    {
        'category': '#caseCards',
        'src1': '../../img/catalog/case/other/nokia/3310-blue.webp',
        'radio1': 'вечного сияния',
        'src2': '../../img/catalog/case/other/nokia/3310-grey.webp',
        'radio2': 'качественный',
        'src3': '../../img/catalog/case/other/nokia/3310-pink.webp',
        'radio3': 'нокийный',
       
       
        'length': 3,
        'alt': 'not',
        'title': 'Nokia 3310',
        'subtitle': 'Lorem ipsum excepturi ipsum dol Dolorem nostrum excepturi 3310',
        'price': 100000,
        'data': '18.06.2004',
        'brand': 'other',
        'id': 22,
    },
    //accessories
    {
        'category': '#accessoriesCards',
        'src1': '../../img/catalog/accesorries/iphone/1/case-brow.jpg',
        'radio1': 'космический',
        'src2': '../../img/catalog/accesorries/iphone/1/case-green.jpg',
        'radio2': 'галактический',
        'src3': '../../img/catalog/accesorries/iphone/1/case-pink.jpg',
        'radio3': 'вселенский',
        'src3': '../../img/catalog/accesorries/iphone/1/case-yellow.jpg',
        'radio3': 'морской',
       
       
        'length': 4,
        'alt': 'not',
        'title': 'Apple case 2',
        'subtitle': 'Lorem ipsum excepturi ipsum dol Dolorem nostrum excepturi 3310 excepturi ipsum dol Dolorem nostrum excepturi 3310',
        'price': 8520,
        'data': '07.09.2021',
        'brand': 'apple',
        'id': 23,
    },
    {
        'category': '#accessoriesCards',
        'src1': '../../img/catalog/accesorries/iphone/2/blue.jpg',
        'radio1': 'гранатовый',
        'src2': '../../img/catalog/accesorries/iphone/2/pink.jpg',
        'radio2': 'лимонный',
        'src3': '../../img/catalog/accesorries/iphone/2/pink1.jpg',
        'radio3': 'апельсиновый',
        'src3': '../../img/catalog/accesorries/iphone/2/white.jpg',
        'radio3': 'виноградный',
       
       
        'length': 4,
        'alt': 'not',
        'title': 'Apple case 22',
        'subtitle': 'Lorem ipsum exceptur  3310 excepturi ipsum dol Dolorem nostrum excepturi 3310',
        'price': 8520,
        'data': '07.11.2022',
        'brand': 'apple',
        'id': 24,
    },
    {
        'category': '#accessoriesCards',
        'src1': '../../img/catalog/accesorries/iphone/3/ipad-bluejpg.jpg',
        'radio1': 'вааилонский',
        'src2': '../../img/catalog/accesorries/iphone/3/ipad-red.jpg',
        'radio2': 'московский',
        'src3': '../../img/catalog/accesorries/iphone/3/ipad-white.jpg',
        'radio3': 'саратовский',
        'src3': '../../img/catalog/accesorries/iphone/3/ipad-yel.jpg',
        'radio3': 'канкунский',
       
       
        'length': 4,
        'alt': 'not',
        'title': 'Apple C 77',
        'subtitle': 'Lorem ipsum exceptur  3310 excepturi ipsum dol Dolorem nostrum excepturi ipsum dol Dolorem nostrum excepturi ipsum dol Dolorem nostrum excepturi',
        'price': 8999,
        'data': '07.04.2023',
        'brand': 'apple',
        'id': 25,
    },
    {
        'category': '#accessoriesCards',
        'src1': '../../img/catalog/accesorries/other/1/1.webp',
        'radio1': 'каннский',
        'src2': '../../img/catalog/accesorries/other/1/2.jpg',
        'radio2': 'мухосранский',
        
       
       
        'length': 2,
        'alt': 'not',
        'title': 'Toy TNT',
        'subtitle': 'Lorem ipsum exceptur   Dolorem nostrum excepturi ipsum dol Dolorem nostrum excepturi ipsum dol Dolorem nostrum excepturi',
        'price': 1234,
        'data': '18.11.1990',
        'brand': 'expensive',
        'id': 26,
    },
    {
        'category': '#accessoriesCards',
        'src1': '../../img/catalog/accesorries/xiomi/1/xi1.webp',
        'radio1': 'ванильный',
        'src2': '../../img/catalog/accesorries/xiomi/1/xi2.webp',
        'radio2': 'красильный',
        
       
       
        'length': 2,
        'alt': 'not',
        'title': 'Xiaomi phuket',
        'subtitle': 'Lorem ipsum exceptur   Dolorem nostrum excepturi ipsum dol Dolorem nostrum excepturi ipsum dol Dolorem nostrum excepturi',
        'price': 6547,
        'data': '19.11.1988',
        'brand': 'xiaomi',
        'id': 27,
    },
    {
        'category': '#accessoriesCards',
        'src1': '../../img/catalog/accesorries/iphone/4/watch1.jpg',
        'radio1': 'валирийский',
        'src2': '../../img/catalog/accesorries/iphone/4/watch2.jpg',
        'radio2': 'джон-сноувский',
        'src3': '../../img/catalog/accesorries/iphone/4/watch3.jpg',
        'radio3': 'волчий',
        'src3': '../../img/catalog/accesorries/iphone/4/watch4.jpg',
        'radio3': 'гаррипоттеровский',
       
       
        'length': 4,
        'alt': 'not',
        'title': 'Apple Watch 66',
        'subtitle': 'Lorem ipsum exceptur   nostrum excepturi',
        'price': 17998,
        'data': '08.11.2023',
        'brand': 'apple',
        'id': 28,
    },
    {
        'category': '#accessoriesCards',
        'src1': '../../img/catalog/accesorries/iphone/5/expensive1.jpg',
        'radio1': 'краснокутский',
        'src2': '../../img/catalog/accesorries/iphone/5/expensive2.jpg',
        'radio2': 'душный',
        'src3': '../../img/catalog/accesorries/iphone/5/expensive3.jpg',
        'radio3': 'спелый',
        'src3': '../../img/catalog/accesorries/iphone/5/expensive4.jpg',
        'radio3': 'гермионный',
       
       
        'length': 4,
        'alt': 'not',
        'title': 'Apple Watch 77',
        'subtitle': 'Lorem ipsum exceptur   nostrum excepturi',
        'price': 19998,
        'data': '08.07.2020',
        'brand': 'apple',
        'id': 29,
    },
    {
        'category': '#accessoriesCards',
        'src1': '../../img/catalog/accesorries/iphone/6/remen1.jpg',
        'radio1': 'краснокутский',
        'src2': '../../img/catalog/accesorries/iphone/6/remen2.jpg',
        'radio2': 'душный',
        
       
       
        'length': 2,
        'alt': 'not',
        'title': 'Apple Clock ',
        'subtitle': 'Lorem ipsum exceptur   nostrum excepturi Lorem ipsum exceptur   nostrum excepturi Lorem ipsum exceptur   nostrum excepturi Lorem ipsum exceptur   nostrum excepturi',
        'price': 27100,
        'data': '06.06.2019',
        'brand': 'apple',
        'id': 30,
    },
    {
        'category': '#accessoriesCards',
        'src1': '../../img/catalog/accesorries/xiomi/2/xi-1.webp',
        'radio1': 'шторный',
        'src2': '../../img/catalog/accesorries/xiomi/2/xi-2.webp',
        'radio2': 'тюльный',
        'src2': '../../img/catalog/accesorries/xiomi/2/xi-3.webp',
        'radio2': 'салатовый',
        
       
       
        'length': 3,
        'alt': 'not',
        'title': 'Xiaomi Clock',
        'subtitle': 'Lorem ipsum exceptur   Dolorem nostrum excepturi ipsum dol Dolorem nostrum excepturi ipsum dol Dolorem nostrum excepturi',
        'price': 1212,
        'data': '19.12.2007',
        'brand': 'xiaomi',
        'id': 31,
    },
    {
        'category': '#accessoriesCards',
        'src1': '../../img/catalog/accesorries/other/2/1.webp',
        'radio1': 'глазный',
        'src2': '../../img/catalog/accesorries/other/2/2.webp',
        'radio2': 'носовый',
        'src2': '../../img/catalog/accesorries/other/2/3.webp',
        'radio2': 'ротовый',
       
       
        'length': 3,
        'alt': 'not',
        'title': 'Other Super Stop',
        'subtitle': 'Lorem ipsum exceptur   Dolorem nostrum excepturi ipsum dol Dolorem nostrum excepturi ipsum dol Dolorem nostrum excepturi',
        'price': 6655,
        'data': '18.12.1999',
        'brand': 'other',
        'id': 32,
    },
    {
        'category': '#accessoriesCards',
        'src1': '../../img/catalog/accesorries/other/3/1.webp',
        'radio1': 'маринованый',
        'src2': '../../img/catalog/accesorries/other/3/2.webp',
        'radio2': 'грибочный',
        'src2': '../../img/catalog/accesorries/other/3/3.webp',
        'radio2': 'пивной',
       
       
        'length': 3,
        'alt': 'not',
        'title': 'Other Great Big',
        'subtitle': 'Lorem ipsum exceptur   Dolorem  ipsum dol Dolorem nostrum excepturi',
        'price': 7859,
        'data': '22.12.2017',
        'brand': 'other',
        'id': 33,
    },
    {
        'category': '#accessoriesCards',
        'src1': '../../img/catalog/accesorries/other/polet/polet1.webp',
        'radio1': 'дорогой',
        'src2': '../../img/catalog/accesorries/other/polet/polet2.webp',
        'radio2': 'знаменитый',
        'src2': '../../img/catalog/accesorries/other/polet/polet3.webp',
        'radio2': 'прилагательный',
       
       
        'length': 3,
        'alt': 'not',
        'title': 'Polet',
        'subtitle': 'Lorem ipsum exceptur   Dolorem  ipsum dol Dolorem nostrum excepturi Lorem ipsum exceptur   Dolorem  ipsum dol Dolorem nostrum excepturi',
        'price': 88888,
        'data': '29.04.2020',
        'brand': 'expensive',
        'id': 34,
    },
]
